Repository SoftDevSix/ArgosApplication, pull requests merged in 2024-12, with the labels that each got.

#36 feat: add repository
  src/main/java/com/softdevsix/application/mappers/json/FileMapper.java
  src/main/java/com/softdevsix/application/services/File/FileService.java
  src/main/java/com/softdevsix/application/services/Project/ProjectService.java
  src/main/java/com/softdevsix/application/services/report/ReportService.java
  src/main/java/com/softdevsix/domain/entities/file/File.java
  src/main/java/com/softdevsix/domain/entities/file/FileCoverageResult.java
  src/main/java/com/softdevsix/domain/entities/file/MethodCoverageResult.java
  src/main/java/com/softdevsix/domain/entities/project/ProjectParams.java
  src/main/java/com/softdevsix/domain/repositories/IProjectRepository.java
  src/main/java/com/softdevsix/domain/repositories/IRulesRepository.java
  src/main/java/com/softdevsix/domain/repositories/ProjectRepository.java
  src/main/java/com/softdevsix/domain/repositories/RulesMemoryRepository.java
  src/main/java/com/softdevsix/presentation/controllers/FileCoverageController.java
  src/test/java/com/softdevsix/application/services/ProjectServiceTest.java
  src/test/java/com/softdevsix/presentation/controllers/FileCoverageControllerTest.java
  src/test/java/com/softdevsix/presentation/controllers/RulesControllerTest.java
Labels: feature

#39 refactor: add path file required project id and file path
  src/main/java/com/softdevsix/application/mappers/json/FileMapper.java
  src/main/java/com/softdevsix/application/services/report/ReportService.java
  src/main/java/com/softdevsix/domain/repositories/FileMemoryRepository.java
  src/main/java/com/softdevsix/domain/repositories/ProjectRepository.java
  src/main/java/com/softdevsix/presentation/controllers/FileCoverageController.java
  src/test/java/com/softdevsix/application/mappers/json/FileMapperTest.java
  src/test/java/com/softdevsix/application/services/report/ReportServiceTest.java
  src/test/java/com/softdevsix/presentation/controllers/FileCoverageControllerTest.java
Labels: refactor

#42 feat: ticket cs-56
  .github/workflows/docker-push.yml
  src/main/java/com/softdevsix/application/dto/CodeAnalysisResultDTO.java
  src/main/java/com/softdevsix/application/dto/CoverageResultDTO.java
  src/main/java/com/softdevsix/application/dto/ProjectParamsRequestDTO.java
  src/main/java/com/softdevsix/application/dto/ProjectResultDTO.java
  src/main/java/com/softdevsix/application/mappers/json/FileMapper.java
  src/main/java/com/softdevsix/application/services/ProjectService.java
  src/main/java/com/softdevsix/application/services/file/FileService.java
  src/main/java/com/softdevsix/application/services/file/IFileService.java
  src/main/java/com/softdevsix/application/services/project/IProjectService.java
  src/main/java/com/softdevsix/application/services/project/ProjectService.java
  src/main/java/com/softdevsix/application/services/report/ReportService.java
  src/main/java/com/softdevsix/application/services/rules/IRulesService.java
  src/main/java/com/softdevsix/application/services/rules/RulesService.java
  src/main/java/com/softdevsix/domain/entities/file/File.java
  src/main/java/com/softdevsix/domain/entities/file/FileCoverageResult.java
  src/main/java/com/softdevsix/domain/entities/file/MethodCoverageResult.java
  src/main/java/com/softdevsix/domain/entities/project/Project.java
  src/main/java/com/softdevsix/domain/entities/project/ProjectParams.java
  src/main/java/com/softdevsix/domain/entities/project/ProjectResults.java
  src/main/java/com/softdevsix/domain/exceptions/BadRequestException.java
  src/main/java/com/softdevsix/domain/repositories/ProjectRepository.java
  src/main/java/com/softdevsix/domain/repositories/file/FileMemoryRepository.java
  src/main/java/com/softdevsix/domain/repositories/file/IFileRepository.java
  src/main/java/com/softdevsix/domain/repositories/project/IProjectRepository.java
  src/main/java/com/softdevsix/domain/repositories/project/ProjectRepository.java
  src/main/java/com/softdevsix/domain/repositories/rules/IRulesRepository.java
  src/main/java/com/softdevsix/domain/repositories/rules/RulesMemoryRepository.java
  src/main/java/com/softdevsix/presentation/controllers/FileCoverageController.java
  src/main/java/com/softdevsix/presentation/controllers/ProjectController.java
  src/main/java/com/softdevsix/presentation/controllers/ProjectMetricsController.java
  src/main/java/com/softdevsix/presentation/controllers/RulesController.java
  src/test/java/com/softdevsix/application/services/FileServiceTest.java
  src/test/java/com/softdevsix/application/services/ProjectServiceTest.java
  src/test/java/com/softdevsix/application/services/RulesServiceTest.java
  src/test/java/com/softdevsix/application/services/report/ReportServiceTest.java
  src/test/java/com/softdevsix/domain/repositories/FileMemoryRepositoryTest.java
  src/test/java/com/softdevsix/domain/repositories/ProjectRepositoryTest.java
  src/test/java/com/softdevsix/domain/repositories/RulesMemoryRepositoryTest.java
  src/test/java/com/softdevsix/presentation/controllers/CoverageNotificationControllerTest.java
  src/test/java/com/softdevsix/presentation/controllers/FileCoverageControllerTest.java
  src/test/java/com/softdevsix/presentation/controllers/ProjectControllerTest.java
  src/test/java/com/softdevsix/presentation/controllers/ProjectMetricsControllerTest.java
  src/test/java/com/softdevsix/presentation/controllers/RulesControllerTest.java
Labels: release

#44 hotfix: append FileManager address to CORS configuration
  src/main/java/com/softdevsix/infrastructure/configuration/cors/CustomCorsConfiguration.java
Labels: bug
